### ISSUE TITLE
TGbot问题

### ISSUE THREAD

**Issue by mslxi** [cokemine/nodestatus#100]
![image](https://user-images.githubusercontent.com/56199297/161831771-e155cbd8-7702-4d4c-9469-793c1ee54580.png)
尝试了几个服务器，在我给TGbot发送/start之后，logs报错，bot无反应
`/usr/lib/node_modules/nodestatus-server/build/app.js:149750
      str = msg.toString();
                ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at parseEntities (/usr/lib/node_modules/nodestatus-server/build/app.js:149750:17)
    at /usr/lib/node_modules/nodestatus-server/build/app.js:149818:40
    at /usr/lib/node_modules/nodestatus-server/build/app.js:63009:111
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async execute (/usr/lib/node_modules/nodestatus-server/build/app.js:63314:17)
    at async /usr/lib/node_modules/nodestatus-server/build/app.js:63315:21
    at async execute (/usr/lib/node_modules/nodestatus-server/build/app.js:63314:17)
    at async execute (/usr/lib/node_modules/nodestatus-server/build/app.js:63314:17)
    at async /usr/lib/node_modules/nodestatus-server/build/app.js:65645:13
`

**Comment by cokemine** [comment]
服务端里有配置添加一个客户端吗

**Comment by mslxi** [comment]
> 服务端有配置添加一个客户端吗
有的，上下线通知没有问题，就是无法使用/start  /status 命令

**Comment by cokemine** [comment]
应该是手动安装的吧，我看看

**Comment by mslxi** [comment]
> 应该是手动安装的吧，我看看

手动安装和docker安装，都在不同机器尝试过，都是一样报错，还申请了一个新的bot尝试，也是同样不行

**Comment by mslxi** [comment]
![image](https://user-images.githubusercontent.com/56199297/161929093-f7475699-9d7e-4d49-b7ad-9190ea4592eb.png)
![image](https://user-images.githubusercontent.com/56199297/161929115-7ffc9ddc-2fdb-45ec-9642-7b88fa3934bc.png)
这是完整截图

**Comment by cokemine** [comment]
我也说不准到底是哪里出问题了（
试试最新的版本？

**Comment by mslxi** [comment]
> 我也说不准到底是哪里出问题了（ 最新的版本？

更新后没有问题了，感谢付出
