### ISSUE TITLE
TG群组中服务器状态显示错误

### ISSUE THREAD

**Issue by whoisxiucai** [cokemine/nodestatus#105]
![image](https://user-images.githubusercontent.com/46469762/165289246-ea2e33c8-b567-4b9f-8be5-c79edeb9e7cb.png)

web端显示正常，服务器都在线，私聊也正常。

docker 日志也没有有效信息。

**Comment by cokemine** [comment]
更新一下镜像试试

**Comment by whoisxiucai** [comment]
> 

可以了，么么哒😘
