### ISSUE TITLE
大佬，换下css的cdn吧，jsdelivr又被DNS污染了

### ISSUE THREAD

**Issue by mutuyi** [cokemine/nodestatus#119]
<img src="https://s1.328888.xyz/2022/05/16/DuA9d.png" alt="DuA9d.png" border="0" />

**Comment by SoraKasvgano** [comment]
同，希望更换为本地资源， 另外可否提供关闭数据库备份功能，运行了半年 数据库备份了900M 小鸡撑不住 :( @cokemine 谢谢dalao

**Comment by SoraKasvgano** [comment]
另外一点  /admin/incidents  小鸡CPU占用率就会超锅100%然后假死

数据库目前大小为13M

**Comment by SoraKasvgano** [comment]
![捕获](https://user-images.githubusercontent.com/8521327/169488400-3455eb38-7b28-450e-a447-f7caee99278c.JPG)

**Comment by cokemine** [comment]
> /admin/incidents

可能是事件太多了。这个页面应该可以一键删除。删除一下吧。。


> 同，希望更换为本地资源， 另外可否提供关闭数据库备份功能，运行了半年 数据库备份了900M 小鸡撑不住 :( @cokemine 谢谢dalao

这个备份功能收益确实不是很大。删掉这个自动备份吧

**Comment by cokemine** [comment]
修复了（

**Comment by cokemine** [comment]
@SoraKasvgano 可以换回默认标签了。
SQLite 数据库文件大小不变是正常的，删除数据默认不会释放占用空间而作为预留空间，再次插入时不会新增占用空间

**Comment by SoraKasvgano** [comment]
> 

收到 谢谢dalao
