### ISSUE TITLE
请问如何让vnstat显示总流量

### ISSUE THREAD

**Issue by Sizukaze** [cokemine/nodestatus#130]
使用nodestatus-client-go
ExecStart=/usr/local/NodeStatus/client/status-client --dsn $DSN -vnstat
试了几台机器好像都只能显示一个月的流量，跟机器直接运行vnstat命令上的total计数差很多。
是否有办法让web页面上显示总流量呢

**Comment by cokemine** [comment]
nodestatus-client-go 是直接写死的计算月流量
你需要修改部分代码重新编译才能显示总流量。
因为 nodestatus-client-go 依赖了 https://github.com/cokemine/ServerStatus-goclient/blob/master/pkg/status/status.go#L103
推荐你克隆下 nodestatus-client-go 然后手动添加一个使用 vnstat 计算的方法
把 `netIn, err := strconv.ParseUint(vData[8], 10, 64)` 改成 `netIn, err := strconv.ParseUint(vData[8], 12, 64)`
`netOut, err := strconv.ParseUint(vData[9], 10, 64)` 改成 `netOut, err := strconv.ParseUint(vData[13], 12, 64)`
然后替换掉原有的 `netIn, netOut, err = status.TrafficVnstat()` 重新编译

**Comment by Sizukaze** [comment]
> 

好的，知道了。谢谢！

**Comment by n0thing2speak** [comment]
能不能加一个显示栏，分别显示月流量和总流量？
