### ISSUE TITLE
请问 nodestatus支持https与各个客户端进行连接吗

### ISSUE THREAD

**Issue by lls275** [cokemine/nodestatus#132]
请问 nodestatus支持https与各个客户端进行连接吗？ 能否添加支持https连接的功能？

**Comment by lls275** [comment]
改成类似“status-client -dsn "https://username:password@localhost"”

**Comment by cokemine** [comment]
https: wss://username:password@status.yourdomain.com
http: ws://username:password@status.yourdomain.com
