### ISSUE TITLE
docker-compose.yml的配置文件是不是有问题？

### ISSUE THREAD

**Issue by hui99995** [cokemine/nodestatus#148]
我修改了里面的二处端口 端口还是占用默认35601的端口，还有web服务的路径写那？

**Comment by hui99995** [comment]
root@HK2:~/nodestatus# docker compose up
[+] Running 1/1
 ⠿ Container nodestatus  Recreated                                                                  0.1s
Attaching to nodestatus
nodestatus  | 2022-09-24T15:33:40: PM2 log: Launching in no daemon mode
nodestatus  | 2022-09-24T15:33:40: PM2 log: App [npm:0] starting in -fork mode-
nodestatus  | 2022-09-24T15:33:40: PM2 log: App [npm:0] online
nodestatus  | > nodestatus@0.0.0 start
nodestatus  | > npm run app:server start
nodestatus  | > nodestatus@0.0.0 app:server
nodestatus  | > pnpm --filter=nodestatus-server "start"
nodestatus  | > nodestatus-server@1.2.6-beta.1 prestart /app/packages/nodestatus-server
nodestatus  | > node scripts/init.js
nodestatus  | Environment variables loaded from prisma/.env
nodestatus  | Prisma schema loaded from prisma/schema.prisma
nodestatus  | Datasource "db": SQLite database "db.sqlite" at "file:/usr/local/NodeStatus/server/db.sqlite"
nodestatus  | The database is already in sync with the Prisma schema.
✔ Generated Prisma Client (3.13.0 | library) to ./../../node_modules/.pnpm/@pris
nodestatus  | ma+client@3.13.0_prisma@3.13.0/node_modules/@prisma/client in 141ms
nodestatus  | Database file location: file:/usr/local/NodeStatus/server/db.sqlite
nodestatus  | > nodestatus-server@1.2.6-beta.1 start /app/packages/nodestatus-server
nodestatus  | > node build/app.js
nodestatus  | [2022-09-24T15:33:46.994] [INFO] default - 🎉  NodeStatus is listening on http://127.0.0.1:35601
nodestatus  | [2022-09-24T15:33:46.995] [INFO] default - 🎉  NodeStatus Ipc is listening on /tmp/status_unix.sock

**Comment by hui99995** [comment]
root@HK2:~# wget http://127.0.0.1:35601
--2022-09-24 15:34:56--  http://127.0.0.1:35601/
Connecting to 127.0.0.1:35601... connected.
HTTP request sent, awaiting response... 200 OK
Length: 401 [text/html]
Saving to: ‘index.html’

index.html   100%     401  --.-KB/s    in 0s

2022-09-24 15:34:56 (61.7 MB/s) - ‘index.html’ saved [401/401]

**Comment by cokemine** [comment]
@hui99995 我这里没有复现这个问题
> nodestatus  | > nodestatus-server@1.2.6-beta.1 start /app/packages/nodestatus-server
nodestatus  | > node build/app.js
nodestatus  | [2022-09-24T16:19:27.703] [INFO] default - 🎉  NodeStatus is listening on http://127.0.0.1:35602


你可能没有删掉原来容器，compose 配置文件要想生效必须删掉原来容器重新启动

尝试先 `docker compose down`

> 还有web服务的路径写那？

这个问题不是很明白

**Comment by hui99995** [comment]
> 



> @hui99995 我这里没有复现这个问题
> 
> > nodestatus  | > nodestatus-server@1.2.6-beta.1 start /app/packages/nodestatus-server
> > nodestatus  | > node build/app.js
> > nodestatus  | [2022-09-24T16:19:27.703] [INFO] default - 🎉  NodeStatus is listening on http://127.0.0.1:35602
> 
> 你可能没有删掉原来容器，compose 配置文件要想生效必须删掉原来容器重新启动
> 
> 尝试先 `docker compose down`
> 
> > 还有web服务的路径写那？
> 
> 这个问题不是很明白



> @hui99995 我这里没有复现这个问题
> 
> > nodestatus  | > nodestatus-server@1.2.6-beta.1 start /app/packages/nodestatus-server
> > nodestatus  | > node build/app.js
> > nodestatus  | [2022-09-24T16:19:27.703] [INFO] default - 🎉  NodeStatus is listening on http://127.0.0.1:35602
> 
> 你可能没有删掉原来容器，compose 配置文件要想生效必须删掉原来容器重新启动
> 
> 尝试先 `docker compose down`
> 
> > 还有web服务的路径写那？
> 
> 这个问题不是很明白

通过docker部署需要配置apache2 或者nginx吗？还是就是web页面的路径写到配置文件的那个位置

**Comment by cokemine** [comment]
前端静态文件现在直接 NodeStatus 接管。

访问 http://127.0.0.1:35601/ 就可以直接使用。只不过如果你需要绑定域名/SSL证书就需要其他的 Web 服务器程序配置反向代理

参考这里 https://github.com/cokemine/nodestatus#reverse-proxy

**Comment by hui99995** [comment]
> 前端静态文件现在直接 NodeStatus 接管。
> 
> 访问 http://127.0.0.1:35601/ 就可以直接使用。只不过如果你需要绑定域名/SSL证书就需要其他的 Web 服务器程序配置反向代理
> 
> 参考这里 https://github.com/cokemine/nodestatus#reverse-proxy

前端文件要改的话在哪改

**Comment by cokemine** [comment]
> > 前端静态文件现在直接 NodeStatus 接管。
> > 访问 http://127.0.0.1:35601/ 就可以直接使用。只不过如果你需要绑定域名/SSL证书就需要其他的 Web 服务器程序配置反向代理
> > 参考这里 https://github.com/cokemine/nodestatus#reverse-proxy
> 
> 前端文件要改的话在哪改

在容器内 /app/packages/nodestatus-server/build/dist/ 里
参考：https://github.com/cokemine/nodestatus/issues/70#issuecomment-1092599607
