### ISSUE TITLE
已解决 

### ISSUE THREAD

**Issue by geshenggang4** [cokemine/nodestatus#167]

**Comment by geshenggang4** [comment]
指的是！安说明操作完成后，没有服务器管理页面！

**Comment by cokemine** [comment]
http://ip地址:35601 无法访问吗？安全组或本地防火墙没有放通这个端口

**Comment by geshenggang4** [comment]
本地服务器 没防火墙的！

**Comment by geshenggang4** [comment]
![5](https://user-images.githubusercontent.com/59082460/208286080-7e2f6bfd-e755-4802-837a-729874146fe2.png)
![1](https://user-images.githubusercontent.com/59082460/208286082-9b5304d0-9ce4-4984-83f4-81fe9327e422.png)
![2](https://user-images.githubusercontent.com/59082460/208286084-623182c7-e39a-475c-b2eb-a6086fc0b036.png)
![3](https://user-images.githubusercontent.com/59082460/208286087-54aa9e1f-4d99-402c-ab22-4608ed6fab10.png)
![4](https://user-images.githubusercontent.com/59082460/208286088-d59f299b-5fae-4a55-b92a-930fb5a2e729.png)
![6](https://user-images.githubusercontent.com/59082460/208286150-16b2dc68-0acb-44e9-84a8-5b01acb00fdd.png)

**Comment by cokemine** [comment]
docker compose logs 看看日志？

**Comment by geshenggang4** [comment]
系统是ubuntu18.04lts版本 我现在来换成本地安装方式 来试试 看看如何

**Comment by geshenggang4** [comment]
![微信截图_20221218153900](https://user-images.githubusercontent.com/59082460/208286914-14bb9a4c-7a0e-4109-b40f-8dd81862278b.png)
报错了！没找到可设置文件在哪

**Comment by geshenggang4** [comment]
![11](https://user-images.githubusercontent.com/59082460/208287786-cdfe24a5-f56a-46bc-94f1-e4ed210402ed.png)
日志报错 这个在哪设置
