### ISSUE TITLE
关于docker运行 yaml文件修改

### ISSUE THREAD

**Issue by toyo2333** [cokemine/nodestatus#215]
我看了下yaml文件里 

    volumes:
      - /usr/local/NodeStatus/server:/usr/local/NodeStatus/server
      - /tmp:/tmp:rw

请问这里 /usr/local/里需要手工创建NodeStatus/server这个目录么？ 以及 /tmp这个是必须的么？

我自己的docker习惯于所有的project下面是以这样的结构放置（一个目录放配置文件相关的，一个目录用于数据持久化，例如：

        volumes:
            - ./caddy/container-data:/data
            - ./caddy/container-config:/config

我改怎么修改呢？我看项目没有什么配置文件，那我就用2个目录分别放置数据库和临时文件，这样可以么？

        volumes:
            - ./nodestatus/container-data:/usr/local/NodeStatus/server
            - ./nodestatus/container-data2:/tmp:rw

**Comment by cokemine** [comment]
- ./nodestatus/container-data2:/tmp:rw 是没必要的，映射/tmp主要是方便在宿主机上用status-cli，如果不需要用[status-cli](https://github.com/cokemine/nodestatus#nodestatus-cli)，就不需要映射这个目录

**Comment by cokemine** [comment]
> > * ./nodestatus/container-data2:/tmp:rw 是没必要的，映射/tmp主要是方便在宿主机上用status-cli，如果不需要用[status-cli](https://github.com/cokemine/nodestatus#nodestatus-cli)，就不需要映射这个目录
> 
> 我是通过web添加节点的 是不是就不用这个了。

是的，但是/usr/local/NodeStatus/server还是要映射的，你可以映射到宿主机任何一个目录比如./data，确保容器重建后数据库文件不丢失就行
