### ISSUE TITLE
两处不明白：nginx 反代和客户端运行

### ISSUE THREAD

**Issue by fscarmen** [cokemine/nodestatus#22]
1.反代应该修改哪个文件呢？ 是 /etc/nginx/nginx.conf 这个吗？ 把你那段修改后放在最后面？

2.客户端，我通过命令行运行了，前面也看到数据，但该命令一直挂着操作不了其他东西，按 Ctrl+C 退出后数据就断开了，如何挂起运行？

**Comment by fscarmen** [comment]
> 1.如果你不是从面板或者其他 LNMP 一件包安装的 Nginx, 你可以看下有没有`/etc/nginx/conf.d/`这个文件夹，如果有一般把单个站点的配置文件放到这里面。然后`nginx -s reload`重载一下配置文件。
> 2.你应该是直接运行的二进制文件，但是仓库已经提供了`service`文件，如果你使用的 Golang 版本，按照 README 写的方法就是直接以服务运行，也就默认配好开机自启动了

第二点，我在服务端同样的VPS选择 Golang版本，
echo 'DSN="wss://username:password@tz.mydomain.com"' > /usr/local/NodeStatus/client/config.conf
wget https://raw.githubusercontent.com/cokemine/nodestatus-client-go/master/service/status-client.service -P /usr/lib/systemd/system/
systemctl enable status-client
systemctl start status-client
systemctl status status-client

我就是设置为DSN="wss://用户名:密码@127.0.0.1" 试过 ws和wss，再运行下面的指令，都起不来，用了CLI的那个倒可以，但不能退出

**Comment by cokemine** [comment]
是否有运行`chmod +x /usr/local/NodeStatus/client/status-client`赋予了正确的权限？
看看这个文件里的配置是不是正确的`/usr/local/NodeStatus/client/config.conf`

**Comment by cokemine** [comment]
> 是否有运行`chmod +x /usr/local/NodeStatus/client/status-client`赋予了正确的权限？
> 看看这个文件里的配置是不是正确的`/usr/local/NodeStatus/client/config.conf`

既然能手动运行说明可执行权限应该是有的🤔

**Comment by fscarmen** [comment]
![image.png](https://i.loli.net/2021/09/20/YzyPTC6dAUt2jmH.png)

**Comment by fscarmen** [comment]
> 是不是开启了 SELinux ? 如果不需要的话把它关掉试试看？

getenforce 显示是 Enforcing，也不用改为 disable了。就是重启vps后正常了

**Comment by fscarmen** [comment]
在IPv6 only的服务上建的实例遇到添加客户端信息后却不显示的问题，如下图
![image.png](https://i.loli.net/2021/09/22/sLT3QJljZykYHBI.png)

**Comment by cokemine** [comment]
will fix soon

**Comment by cokemine** [comment]
@fscarmen 
我这边测试没有问题，能否提供更多信息？比如是否使用了反代？
打开前端 F12 看看控制台报了什么错

**Comment by fscarmen** [comment]
安装了宝塔面板，用了反代，为域名申请了SSL证书，同时问问在不用CDN的前提下，https 访问不了的，必须是 http。至于前端  F12 我不会看

![image.png](https://i.loli.net/2021/09/22/Muj6nlT3eW8FVCs.png)
![image.png](https://i.loli.net/2021/09/22/KudfgMamb7sPLoD.png)
![image.png](https://i.loli.net/2021/09/22/7kfMLBDraFTmgRZ.png)

**Comment by cokemine** [comment]
> 安装了宝塔面板，用了反代，为域名申请了SSL证书，同时问问在不用CDN的前提下，https 访问不了的，必须是 http，客户端CLI运行的话，也只有 ws可以，用wss不行 。至于前端 F12 我不会看
> 
> ![image.png](https://camo.githubusercontent.com/ad36022aae3c793532b87fa1a3caca260fe7d8956d77dc2462ceceba8a0045b5/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30392f32322f4d756a366e6c5433655738465643732e706e67)
> ![image.png](https://camo.githubusercontent.com/349d40efd820e9a8039343156ec1ee271822a820693c4b3d7a8690d30e62e72a/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30392f32322f4b756466674d616d623773504c6f442e706e67)
> ![image.png](https://camo.githubusercontent.com/ee4f5b522bbc435466ffe7ffc1ea2c42b07c4222e91270f769f9f1ace79e91cb/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30392f32322f376b664d4c4244726146546d67525a2e706e67)
> ![image.png](https://camo.githubusercontent.com/11bcdb9f5f7f5f0d89065bf139b9f37ed9bbf56043ea0134f9bdb48c46ba8196/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30392f32322f6b6242797375616e396d6972586c352e706e67)

点开 public 和 `Console`看看

**Comment by fscarmen** [comment]
现在又可以用https访问了，而且申请的SSL证书生效了，之前可能需要时间没有更新好而已
新增的被监控客户端仍然看不到，之前试过另一个vps搭建的服务端，即使没有数据，也会显示有该信息和离线的
public 找不到是哪里，网址是  s.formyvmess.tk
![image.png](https://i.loli.net/2021/09/22/l7Daq2AHSto1mKN.png)

**Comment by cokemine** [comment]
@fscarmen 
我装了个宝塔测试了一下，宝塔面板的反代默认不会提升 Websocket 协议，你需要手动加入。
宝塔的反代处有个配置文件，你把这两段加上去保存就可以了
加到在`location /`块里
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";

**Comment by fscarmen** [comment]
> @fscarmen
> 我装了个宝塔测试了一下，宝塔面板的反代默认不会提升 Websocket 协议，你需要手动加入。
> 宝塔的反代处有个配置文件，你把这两段加上去保存就可以了
> 加到在`location /`块里
> 
> ```
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "Upgrade";
> ```

果然可以了，厉害。
三个问题仍然需要了解一下：
1、如不用宝塔，申请证书和反代这块分别是用 acme的指令和 apt -y install nginx，然后改nginx.conf，把你项目那段反代复制进去吗？
2、我仍然是用 ws 才行，用 wss 不行，要在本地运行 ./status-client -dsn wss://EUserv:123456@127.0.0.1:35601
提示 Caught Exception: tls: first record does not look like a TLS handshake，客户端与服务端是不是用 wss 安全点的
3、在nginx里作反代，与另一方案：把端口设置为80， ports:- "80:35601"，然后 cloudflare 打开小彩云用CDN，哪个好点呢？

**Comment by fscarmen** [comment]
本地客户端可以了，另一台客户端又遇到问题，一直连接不了，ping一下域名和IP又是通的，无论用ws或者wss都不可以

![image.png](https://i.loli.net/2021/09/22/EgVRMD9e2uW6d7m.png)

**Comment by cokemine** [comment]
> 本地客户端可以了，另一台客户端又遇到问题，一直连接不了，ping一下域名和IP又是通的，无论用ws或者wss都不可以
> 
> ![image.png](https://camo.githubusercontent.com/a19ab67f6bf23fa95b0f17578f360b7b56a82b460c16e9cb54b24ce70489b6b7/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30392f32322f456756524d4439653275573664376d2e706e67)

你开了反代就不需要加端口了，反代后端口就是80或者443。

**Comment by cokemine** [comment]
> > @fscarmen
> > 我装了个宝塔测试了一下，宝塔面板的反代默认不会提升 Websocket 协议，你需要手动加入。
> > 宝塔的反代处有个配置文件，你把这两段加上去保存就可以了
> > 加到在`location /`块里
> > ```
> > proxy_set_header Upgrade $http_upgrade;
> > proxy_set_header Connection "Upgrade";
> > ```
> 
> 果然可以了，厉害。
> 三个问题仍然需要了解一下：
> 1、如不用宝塔，申请证书和反代这块分别是用 acme的指令和 apt -y install nginx，然后改nginx.conf，把你项目那段反代复制进去吗？
> 2、我仍然是用 ws 才行，用 wss 不行，要在本地运行 ./status-client -dsn wss://EUserv:123456@127.0.0.1:35601
> 提示 Caught Exception: tls: first record does not look like a TLS handshake，客户端与服务端是不是用 wss 安全点的
> 3、在nginx里作反代，与另一方案：把端口设置为80， ports:- "80:35601"，然后 cloudflare 打开小彩云用CDN，哪个好点呢？

1. 默认源 Nginx 版本太低，一般用 Nginx 提供的源去安装 Nginx `http://nginx.org/packages/debian` 你可以看下有没有/etc/nginx/conf.d/这个文件夹，如果有一般把单个站点的配置文件放到这里面。然后nginx -s reload重载一下配置文件。
2. wss 对应的是 https，ws 对应 http 本地通信一般没有必要 TLS 加密通信
3. 如果需要使用 CDN， 建议本地先反代 开启 TLS 后，再在 CDN服务商进行配置

**Comment by cokemine** [comment]
这个项目下一个版本可能有不兼容性的数据库结构大改🤔

**Comment by fscarmen** [comment]
>  @cokemine 
>  你开了反代就不需要加端口了，反代后端口就是80或者443。

客户端可以了，的确不需要加端口了，也可以用 https 对应的 wss 了，感谢你的项目和耐心解答！
