### ISSUE TITLE
节点用户名不能用一样的?

### ISSUE THREAD

**Issue by fcying** [cokemine/nodestatus#23]
web 添加节点的Username时, 如果前面有一样的Username, 
会报
500 Internal Server Error
Validation error

**Comment by cokemine** [comment]
这是符合预期的。节点用户名必须是唯一的，要不然无法分辨两个不同的服务器。

ps: 这个项目目前还属于 alpha 版，可能会有及大破坏性变动，望知悉

**Comment by fcying** [comment]
好吧. 那看来用户名要设成主机名了. 方便识别.
