### ISSUE TITLE
更新镜像后出错~~

### ISSUE THREAD

**Issue by lion-goose** [cokemine/nodestatus#29]
今天更新镜像后，首先数据库连接不上，节点全部没了。
docker compose down，又删除数据文件后重新部署。
添加节点后还是连接不上。
status-client[5660]: 2021/10/07 11:24:26 Authentication required
Oct 07 11:24:26 status-client[5660]: 2021/10/07 11:24:26 You are banned. Please try connecting after 60 / 120 seconds
Oct 07 11:24:31 status-client[5660]: 2021/10/07 11:24:31 Authentication required
Oct 07 11:24:31 status-client[5660]: 2021/10/07 11:24:31 You are banned. Please try connecting after 60 / 120 seconds

这个“You are banned.”，该怎么理解，服务端封禁了这个客户端吗？

**Comment by lion-goose** [comment]
呃...是我草率了，差不多5分钟，慢慢就陆续都连上了，可能是反应有点慢吧。。。。
还有就是，通过 Web 面板Import ServerStatus 的 JSON文件，"disabled": false这个字段也不可以有，不然会出错。
类似这样就可以
[
		{
			"username": "s01",
			"password": "password",
			"name": "Mainserver 1",
			"type": "Dedicated Server",
			"location": "America",
			"region":"US"
		},
		{
			"username": "bs01",
			"password": "password",
			"name": "Backupserver 1",
			"type": "Virtual Server",
			"location": "Japan",
			"region":"JP"
		}
	]

**Comment by SoraKasvgano** [comment]
同。。。watchtower更新后在management提示
```
500 Internal Server Error
Inconsistent column data: Conversion failed: input contains invalid characters
```

**Comment by cokemine** [comment]
@SoraKasvgano 是的。1.2.0对数据库结构做了不兼容的更新。之后应该不会有不兼容的改变了
