### ISSUE TITLE
arm进入后台添加小鸡的管理界面报错

### ISSUE THREAD

**Issue by railway7** [cokemine/nodestatus#30]
用的是docker装的，错误日志如下：

500
Unknown PRISMA_QUERY_ENGINE_LIBRARY undefined. Possible binaryTargets: darwin, darwin-arm64, debian-openssl-1.0.x, debian-openssl-1.1.x, rhel-openssl-1.0.x, rhel-openssl-1.1.x, linux-arm64-openssl-1.1.x, linux-arm64-openssl-1.0.x, linux-arm-openssl-1.1.x, linux-arm-openssl-1.0.x, linux-musl, linux-nixos, windows, freebsd11, freebsd12, openbsd, netbsd, arm, native or a path to the query engine library. You may have to run prisma generate for your changes to take effect.

**Comment by cokemine** [comment]
@railway7 我没有机器可以测试，重新拉一下镜像试试现在可以了吗？
