### ISSUE TITLE
进入admin后台登录界面401验证报错

### ISSUE THREAD

**Issue by dmcimi** [cokemine/nodestatus#48]
![9090](https://user-images.githubusercontent.com/61643603/140013631-fc6465be-fb83-4796-bd51-919a9d2246e8.JPG)
希望能解决下。

**Comment by cokemine** [comment]
这个背景资源文件好像被https://github.com/cokemine/nodestatus/commit/e47ee0a266eef6f4cc6be7e386e5a4895a659d78搞崩了。
但是正常登录如果账号密码正确应该不会 401 错误的，你再试下？
晚上修复

**Comment by dmcimi** [comment]
没设置密码和设置密码都尝试了，一样出现401。

**Comment by cokemine** [comment]
修改环境变量后需要重启一下服务，修改密码后你有重启过吗？

**Comment by dmcimi** [comment]
没有直接修改，而是重建再输有密码的，系统也重新换过后做的前一部。

**Comment by dmcimi** [comment]
是在进入/admin后台是出现的401，登录是可以登录的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月3日(周三) 晚上11:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cokemine/nodestatus] 进入admin后台登录界面401验证报错 (Issue #48)




 
@dmcimi 也就是说 在 点击登录之后提示的信息不是username or password is incorrect而是Verification failure是吗？

**Comment by cokemine** [comment]
@dmcimi 那这个是正常现象，因为输入`/admin`默认会进入`/admin/dashboard`因为没有登陆的情况下无权访问这个页面所以会出现`Verification failure`

**Comment by dmcimi** [comment]
😅那还修吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月3日(周三) 晚上11:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cokemine/nodestatus] 进入admin后台登录界面401验证报错 (Issue #48)




 
@dmcimi 那这个是正常现象，因为输入/admin默认会进入/admin/dashboard因为没有登陆的情况下无权访问这个页面所以会出现Verification failure

**Comment by cokemine** [comment]
默认的 token 有效期是 7 天，登陆后 7 天内是会记住密码的也就应该不会出现 `Verification failure` 而是 `Success`
