### ISSUE TITLE
Telegram Bot 异常

### ISSUE THREAD

**Issue by RSSYLY** [cokemine/nodestatus#52]
无法正常识别群组id。当在群组（不论是否公开群组且已给管理员）里使用命令 /status 时，即使id已写入配置文件，但仍提示没有权限，而直接使用 /start 会导致机器人卡住，此时私聊bot无反应。直接私聊bot时命令一切正常

**Comment by cokemine** [comment]
群组的 chat id 有个`-`符号，会导致 Telegram parse Markdown 的时候爆炸
