### ISSUE TITLE
请问在railway中部署后，如何连接数据库

### ISSUE THREAD

**Issue by pzcn** [cokemine/nodestatus#53]
![image](https://user-images.githubusercontent.com/29601158/141432501-2f0db28d-5ca1-443f-9fe6-edd8084b5619.png)
在railway部署后，修改自动重新部署后，数据会丢失。考虑是数据库的原因。我选择了mysql插件，DATABASE填写了插件的地址，看日志也没有问题，但是最后没有效果。想知道预期的效果是什么样

**Comment by cokemine** [comment]
默认使用的 Sqlite 在这里没有办法储存数据。支持多种数据库在考虑范围内

**Comment by pzcn** [comment]
请问后台的Statistics和Alert空白目前正常吗

**Comment by cokemine** [comment]
正常的。这个功能目前还没有（以后可能会有

**Comment by pzcn** [comment]
好的 谢谢，我还以为是数据库的原因xd

**Comment by cokemine** [comment]
这个功能已经在 v1.2.1-beta 实现
