### ISSUE TITLE
关于容器部署数据库链接

### ISSUE THREAD

**Issue by Duan-rax** [cokemine/nodestatus#60]
我在其他服务器上新建了个mysql数据库，并且已经开放公网访问 
目前我只有以下数据
**ip**  **port** **root and password**
请问在env中应该如何详细填写
DATABASE: mysql:

**Comment by cokemine** [comment]
mysql://root:password@ip:port/数据库名

**Comment by Duan-rax** [comment]
竟然秒回，太感谢了，期待项目发展越来越好

**Comment by cokemine** [comment]
（（
