### ISSUE TITLE
有部分节点突然出现Caught Exception错误

### ISSUE THREAD

**Issue by lion-goose** [cokemine/nodestatus#68]
Jan 05 09:41:58 Az-liongoose status-client[1629]: 2022/01/05 09:41:58 Caught Exception: dial tcp: lookup on 127.0.0.5

**Comment by cokemine** [comment]
线路不稳定时可能会出现掉线情况，如果导致了多次错误推送掉线，可以适当提高 PUSH_TIMEOUT

**Comment by lion-goose** [comment]
可能是DNS解析出了问题吧，在hosts文件添加了域名和IP，就又连上了.......
