### ISSUE TITLE
希望可以自定义前端静态文件

### ISSUE THREAD

**Issue by xiqoqi** [cokemine/nodestatus#70]
使用的是docker部署方式，部署完发现映射目录里只有一个数据库文件，希望能够自定义前端静态文件

顺便问一句管理面板可不可以适配中文的

**Comment by cokemine** [comment]
https://github.com/cokemine/nodestatus/issues/47#issuecomment-956290378

**Comment by Masterain98** [comment]
> [#47 (comment)](https://github.com/cokemine/nodestatus/issues/47#issuecomment-956290378)

按照这个方法操作后`/build/dist/config.js`是个空文件（也没有这个目录），请问能提示一下该怎么写内容？

**Comment by cokemine** [comment]
> > [#47 (comment)](https://github.com/cokemine/nodestatus/issues/47#issuecomment-956290378)
> 
> 按照这个方法操作后`/build/dist/config.js`是个空文件（也没有这个目录），请问能提示一下该怎么写内容？

以此版本更新把这个删掉了。之后会找一个更好的办法自定义前端一些内容

**Comment by Masterain98** [comment]
> > > [#47 (comment)](https://github.com/cokemine/nodestatus/issues/47#issuecomment-956290378)
> > 
> > 
> > 按照这个方法操作后`/build/dist/config.js`是个空文件（也没有这个目录），请问能提示一下该怎么写内容？
> 
> 一次版本更新把这个删掉了。之后会找一个更好的办法自定义前端一些内容

有没有办法能让样式文件挂载在主机目录中？

我刚刚自己试了一下，现在编译好的样式文件是在`/app/packages/nodestatus-server/build/dist/hotaru-theme/`中，可以先启动一次容器后`docker cp`把这个目录复制出来。然后在新的容器中挂载这里目录，这样可以暂时达到目标。

**Comment by cokemine** [comment]
> > > > [#47 (comment)](https://github.com/cokemine/nodestatus/issues/47#issuecomment-956290378)
> > > 
> > > 
> > > 按照这个方法操作后`/build/dist/config.js`是个空文件（也没有这个目录），请问能提示一下该怎么写内容？
> > 
> > 
> > 一次版本更新把这个删掉了。之后会找一个更好的办法自定义前端一些内容
> 
> 有没有办法能让样式文件挂载在主机目录中？
> 
> 我刚刚自己试了一下，现在编译好的样式文件是在`/app/packages/nodestatus-server/build/dist/hotaru-theme/`中，可以先启动一次容器后`docker cp`把这个目录复制出来。然后在新的容器中挂载复制出来的目录，这样可以暂时达到目标。

这样是可以的。但是如果镜像里的前端有变化，如果挂载了前端的目录，前端会没有变化。而且打包后的文件会不方便修改。
