### ISSUE TITLE
最新版本后台服务器添加节点后，前段不显示

### ISSUE THREAD

**Issue by szsyzx** [cokemine/nodestatus#72]
最新版本后台加节点后，前段不显示。求助

**Comment by szsyzx** [comment]
![11.jpg](https://s2.loli.net/2022/01/17/COpQFLjKT5mBAvh.jpg)
![22.jpg](https://s2.loli.net/2022/01/17/w8MQLA6da1Ct2gy.jpg)
![33.jpg](https://s2.loli.net/2022/01/17/hC8VZSkxgNcBoLE.jpg)

**Comment by cokemine** [comment]
检查一下反代是否允许了 Websocket

**Comment by szsyzx** [comment]
我用的是宝塔面板的反代

**Comment by cokemine** [comment]
https://github.com/cokemine/nodestatus/issues/22#issuecomment-924830572

**Comment by szsyzx** [comment]
大大面板显示了
客户端显示服务成功启动   ：[信息] NodeStatus Client 启动成功！

但是面板显示离线，请问如何排查问题呢

**Comment by szsyzx** [comment]
![44.jpg](https://s2.loli.net/2022/01/17/pszg5XTq6ZmtF32.jpg)
