### ISSUE TITLE
请问服务端是不是不支持ARM吗【Oracle Cloud】

### ISSUE THREAD

**Issue by szsyzx** [cokemine/nodestatus#74]
![121.jpg](https://s2.loli.net/2022/01/20/A96Iy4frCYcl2eb.jpg)
![122.jpg](https://s2.loli.net/2022/01/20/8POdL5VSYAtXuxD.jpg)

**Comment by cokemine** [comment]
https://github.com/cokemine/nodestatus/issues/30
