### ISSUE TITLE
更新最新docker版本后，一直不停推送断开和重连信息

### ISSUE THREAD

**Issue by lion-goose** [cokemine/nodestatus#91]
PUSH_TIMEOUT设置到120s也不行，
差不多1分钟一次的频率推送断开再重连报警信息

**Comment by cokemine** [comment]
@lion-goose 更新一下最新的客户端 https://github.com/cokemine/nodestatus-client-go

**Comment by lion-goose** [comment]
> @lion-goose 更新一下最新的客户端 https://github.com/cokemine/nodestatus-client-go

多谢大佬，更新客户端马上就恢复正常了
