### ISSUE TITLE
MySQL SLL 连接

### ISSUE THREAD

**Issue by aiastia** [cokemine/nodestatus#96]
Error: Migration engine error:
unknown error: Code: UNAVAILABLE
server does not allow insecure connections, client must use SSL/TLS
Something wrong while updating database schema.

**Comment by aiastia** [comment]
如果数据 有ssl 加密比如 https://app.planetscale.com 

必须加上  ?ssl={"rejectUnauthorized":true}
 但是 nodestatus 无法使用。。。

**Comment by cokemine** [comment]
后面加上 `&sslcert=/etc/ssl/cert.pem`试试

**Comment by aiastia** [comment]
可以了 
mysql://**:**:3306/railway?ssl={"rejectUnauthorized":true}&sslcert=/etc/ssl/cert.pem
